name: Bug report
description: Report a problem with coderabbit.nvim
labels: [bug]
body:
  - type: textarea
    attributes:
      label: "Description"
      description: "A short description of the problem."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Steps to reproduce"
      placeholder: |
        1. Open a file with diagnostics
        2. ...
  - type: textarea
    attributes:
      label: "Expected behavior"
  - type: textarea
    attributes:
      label: "Checkhealth output"
      description: "Output of `:checkhealth coderabbit`"
      render: markdown
    validations:
      required: true
